### ISSUE TITLE
After installing, magento throws exception: Asset has to implement \Magento\Framework\View\Asset\MergeableInterface.

### ISSUE THREAD

**Issue by parchmntpress** [quickshiftin/mage2-ordered-assets#11]
1 exception(s):
Exception #0 (InvalidArgumentException): Asset has to implement \Magento\Framework\View\Asset\MergeableInterface.

Exception #0 (InvalidArgumentException): Asset has to implement \Magento\Framework\View\Asset\MergeableInterface.
<pre>#1 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\Framewor...', array(&Magento\Framework\Logger\Monolog#0000000000d58962000000000be59658#, &Magento\Framework\View\Asset\MergeStrategy\Checksum#0000000000d58f49000000000be59658#, &Magento\Framework\View\Asset\Repository#0000000000d58860000000000be59658#, array('mage/calendar.cs...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1e000000000be59658#, 'MGS_Mmegamenu::c...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f0a000000000be59658#, 'MGS_Promobanners...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f0b000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1d000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f10000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f15000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f12000000000be59658#, 'Magento_Swatches...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f17000000000be59658#, 'css/bootstrap.mi...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4f000000000be59658#, 'css/font-awesome...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f11000000000be59658#, 'css/pe-icon-7-st...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f56000000000be59658#, 'css/menu.css' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1c000000000be59658#, 'css/theme_defaul...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1f000000000be59658#, 'css/theme.css' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58e62000000000be59658#, 'css/responsive.c...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4b000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f18000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4d000000000be59658#, 'MGS_InstantSearc...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4e000000000be59658#), NULL)) called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#2 Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\Framewor...', array('assets' => array('mage/calendar.cs...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1e000000000be59658#, 'MGS_Mmegamenu::c...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f0a000000000be59658#, 'MGS_Promobanners...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f0b000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1d000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f10000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f15000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f12000000000be59658#, 'Magento_Swatches...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f17000000000be59658#, 'css/bootstrap.mi...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4f000000000be59658#, 'css/font-awesome...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f11000000000be59658#, 'css/pe-icon-7-st...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f56000000000be59658#, 'css/menu.css' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1c000000000be59658#, 'css/theme_defaul...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1f000000000be59658#, 'css/theme.css' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58e62000000000be59658#, 'css/responsive.c...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4b000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f18000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4d000000000be59658#, 'MGS_InstantSearc...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4e000000000be59658#), 'mergeStrategy' => &Magento\Framework\View\Asset\MergeStrategy\Checksum#0000000000d58f49000000000be59658#)) called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#3 Magento\Framework\ObjectManager\ObjectManager->create('Magento\Framewor...', array('assets' => array('mage/calendar.cs...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1e000000000be59658#, 'MGS_Mmegamenu::c...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f0a000000000be59658#, 'MGS_Promobanners...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f0b000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1d000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f10000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f15000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f12000000000be59658#, 'Magento_Swatches...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f17000000000be59658#, 'css/bootstrap.mi...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4f000000000be59658#, 'css/font-awesome...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f11000000000be59658#, 'css/pe-icon-7-st...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f56000000000be59658#, 'css/menu.css' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1c000000000be59658#, 'css/theme_defaul...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1f000000000be59658#, 'css/theme.css' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58e62000000000be59658#, 'css/responsive.c...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4b000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f18000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4d000000000be59658#, 'MGS_InstantSearc...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4e000000000be59658#), 'mergeStrategy' => &Magento\Framework\View\Asset\MergeStrategy\Checksum#0000000000d58f49000000000be59658#)) called at [vendor/magento/framework/View/Asset/MergeService.php:92]
#4 Magento\Framework\View\Asset\MergeService->getMergedAssets(array('mage/calendar.cs...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1e000000000be59658#, 'MGS_Mmegamenu::c...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f0a000000000be59658#, 'MGS_Promobanners...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f0b000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1d000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f10000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f15000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f12000000000be59658#, 'Magento_Swatches...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f17000000000be59658#, 'css/bootstrap.mi...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4f000000000be59658#, 'css/font-awesome...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f11000000000be59658#, 'css/pe-icon-7-st...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f56000000000be59658#, 'css/menu.css' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1c000000000be59658#, 'css/theme_defaul...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1f000000000be59658#, 'css/theme.css' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58e62000000000be59658#, 'css/responsive.c...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4b000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f18000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4d000000000be59658#, 'MGS_InstantSearc...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4e000000000be59658#), 'css') called at [vendor/magento/framework/View/Page/Config/Renderer.php:276]
#5 Magento\Framework\View\Page\Config\Renderer->processMerge(array('mage/calendar.cs...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1e000000000be59658#, 'MGS_Mmegamenu::c...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f0a000000000be59658#, 'MGS_Promobanners...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f0b000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1d000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f10000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f15000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f12000000000be59658#, 'Magento_Swatches...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f17000000000be59658#, 'css/bootstrap.mi...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4f000000000be59658#, 'css/font-awesome...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f11000000000be59658#, 'css/pe-icon-7-st...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f56000000000be59658#, 'css/menu.css' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1c000000000be59658#, 'css/theme_defaul...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f1f000000000be59658#, 'css/theme.css' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58e62000000000be59658#, 'css/responsive.c...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4b000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f18000000000be59658#, 'MGS_Mpanel::css/...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4d000000000be59658#, 'MGS_InstantSearc...' => &Quickshiftin\Assetorderer\View\Asset\File#0000000000d58f4e000000000be59658#), &Magento\Framework\View\Asset\PropertyGroup\Interceptor#0000000000d58e5b000000000be59658#) called at [vendor/quickshiftin/assetorderer/View/Page/Config/Renderer.php:40]
#6 Quickshiftin\Assetorderer\View\Page\Config\Renderer->renderAssetHtml(&Magento\Framework\View\Asset\PropertyGroup\Interceptor#0000000000d58e5b000000000be59658#) called at [vendor/magento/framework/View/Page/Config/Renderer.php:261]
#7 Magento\Framework\View\Page\Config\Renderer->renderAssetGroup(&Magento\Framework\View\Asset\PropertyGroup\Interceptor#0000000000d58e5b000000000be59658#) called at [vendor/quickshiftin/assetorderer/View/Page/Config/Renderer.php:28]
#8 Quickshiftin\Assetorderer\View\Page\Config\Renderer->renderAssets(array('css' => '', 'ico' => '', 'js' => '')) called at [vendor/magento/framework/View/Page/Config/Renderer.php:101]
#9 Magento\Framework\View\Page\Config\Renderer->renderHeadContent() called at [vendor/magento/framework/View/Result/Page.php:249]
#10 Magento\Framework\View\Result\Page->render(&Magento\Framework\App\Response\Http\Interceptor#0000000000d58942000000000be59658#) called at [vendor/magento/framework/View/Result/Layout.php:170]
#11 Magento\Framework\View\Result\Layout->renderResult(&Magento\Framework\App\Response\Http\Interceptor#0000000000d58942000000000be59658#) called at [vendor/magento/framework/Interception/Interceptor.php:58]
#12 MGS\Mpanel\Block\Framework\Page\Interceptor->___callParent('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#0000000000d58942000000000be59658#)) called at [vendor/magento/framework/Interception/Interceptor.php:138]
#13 MGS\Mpanel\Block\Framework\Page\Interceptor->Magento\Framework\Interception\{closure}(&Magento\Framework\App\Response\Http\Interceptor#0000000000d58942000000000be59658#) called at [vendor/magento/framework/Interception/Interceptor.php:153]
#14 MGS\Mpanel\Block\Framework\Page\Interceptor->___callPlugins('renderResult', array(&Magento\Framework\App\Response\Http\Interceptor#0000000000d58942000000000be59658#), array(array('result-messages', 'result-builtin-c...', 'result-varnish-c...'))) called at [generated/code/MGS/Mpanel/Block/Framework/Page/Interceptor.php:39]
#15 MGS\Mpanel\Block\Framework\Page\Interceptor->renderResult(&Magento\Framework\App\Response\Http\Interceptor#0000000000d58942000000000be59658#) called at [vendor/magento/framework/App/Http.php:140]
#16 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:257]
#17 Magento\Framework\App\Bootstrap->run(&Magento\Framework\App\Http\Interceptor#0000000000d5894c000000000be59658#) called at [index.php:39]
</pre>

**Comment by quickshiftin** [comment]
Hi, @parchmntpress this looks like it could be a new issue. Which version of Magento are you using?

**Comment by parchmntpress** [comment]
v 2.2.8, running on PHP 7.1.29.

**Comment by pauldonnelly** [comment]
Having the same issue on M2.3.2. When I enable Minify and Merge CSS/JS, I get that error. When I disable Quickshiftin_Assetorderer it works again.
Running PHP 7.1.30

**Comment by quickshiftin** [comment]
Hi @parchmntpress , @pauldonnelly sorry for delay in jumping on this, work has been _crazy_ lately. Looking into it now, the extension is working for me on an install of M2.2.6. Please try these steps to repro and let me know if they solve or where things break:

1. Check composer.json, if you see `"quickshiftin/assetorderer": "dev-master"`, update the package: `composer.phar update quickshiftin/assetorderer`. Afterwords, your main composer.json file should show `"quickshiftin/assetorderer": "^1.1"`; you can also take a deeper look in the composer.json file of the package `vendor/quickshiftin/assetorderer/composer.json`, you should see `"version": "1.1.3"`

2. From the command line run:
```
bin/magento setup:upgrade
rm -rf generated/code/*
bin/magento setup:di:compile
```

3. Test

**Comment by parchmntpress** [comment]
Hi Nathan,
Life is crazy :)
We were already at at ^1.1 in the main composer.json and 1.1.3 in the deeper dive of the assetorderer/composer.json. I actually haven’t tested it in v.2.2.9 yet, so I’ll write back after we give it a better examination. Thanks!

On Aug 6, 2019, at 11:07 AM, Nathan Nobbe <notifications@github.com> wrote:

Hi @parchmntpress <https://github.com/parchmntpress> , @pauldonnelly <https://github.com/pauldonnelly> sorry for delay in jumping on this, work has been crazy lately. Looking into it now, the extension is working for me on an install of M2.2.6. Please try these steps to repro and let me know if they solve or where things break:

Check composer.json, if you see "quickshiftin/assetorderer": "dev-master", update the package: composer.phar update quickshiftin/assetorderer. Afterwords, your main composer.json file should show "quickshiftin/assetorderer": "^1.1"; you can also take a deeper look in the composer.json file of the package vendor/quickshiftin/assetorderer/composer.json, you should see "version": "1.1.3"

From the command line run:

bin/magento setup:upgrade
rm -rf generated/code/*
bin/magento setup:di:compile
Test

**Comment by quickshiftin** [comment]
Hi @parchmntpress @pauldonnelly I have patched the issue and v1.1.4 is hot off the presses! Please give it a try (same instructions from yesterday, except deep dive package version should be 1.1.4) and let me know if working on your end.

**Comment by pauldonnelly** [comment]
Looks all good now @quickshiftin, working on 2.3.2. 
Thanks for the prompt fix!

**Comment by quickshiftin** [comment]
Great to hear @pauldonnelly thanks for letting me know. @parchmntpress if you could also confirm this works for you I will close out the issue.

**Comment by quickshiftin** [comment]
@parchmntpress Sorry again for the delay on this patch! I'm going to close the issue. Feel free to reopen next time you have a chance to try the latest if it's still not working.
