### ISSUE TITLE
Still necessary?

### ISSUE THREAD

**Issue by tehXor** [quickshiftin/mage2-ordered-assets#2]
I just installed your module and found out (by accident) that the order of my CSS files was influenced by an "order" attribute just like stated in your readme.md even before your module was activated. 
I'm not sure though, because I couldn't find anything related CSS ordering in the official magento documentation and when this happened I already had your module files in my installation. But without running magento setup:upgrade and magento setup:di:compile. I'm still new to Magento 2 so I have no idea if this means your module was totally ineffective at that point or not.

So as you wrote this and have deeper insights, is this module still necessary if we want to change the CSS order by specifying an order attribute in layout files?

**Comment by quickshiftin** [comment]
I'm working on a new installation of Magento 2.1. I'll try to test and see if this is the case and circle back soon.

**Comment by xnhinzkyx** [comment]
I think this is not necessary IMO because it still works without using this module but still thanks for this great module. Good job!

**Comment by quickshiftin** [comment]
Hi guys, I finally checked on this with a 2.1 version of Magento and it looks like there still is no built in support for asset ordering. You might want to double-check on your end!

In short, without the module, assets are not ordered, as soon as the module is installed, they are ordered.

I updated the module today, putting it on packagist and cleaning up the installation instructions.

**Comment by xnhinzkyx** [comment]
Yeah I tried it the updated version and it works great!
