### ISSUE TITLE
Invalid Document: Title is Required but missing

### ISSUE THREAD

**Issue by Aresinho** [quickshiftin/mage2-ordered-assets#7]
On Magento 2.2.0 after downloading the source code with composer, trying to run

`php bin/magento setup:upgrade`

returns the following error:

```
Running schema recurring...Invalid Document 
Element 'resource': The attribute 'title' is required but missing.
Line: 5
```

after compiling magento marks an error asking run setup:upgrade

**Comment by AJMaxwell** [comment]
The `<resource>` tag in `/vendor/quickshiftin/assetorderer/etc/acl.xml` is missing a `title` attribute. I know you're technically not supposed to modify files in `/vendor`, however you can edit the file to temporarily solve the problem until a proper fix has been published.

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../lib/internal/Magento/Framework/Acl/etc/acl.xsd">
    <acl>
        <resources>
            <resource id="Magento_Adminhtml::admin" title="AOAdmin">
                <!--AddMenuAcl-->
            </resource>
        </resources>
    </acl>
</config>
```

I chose `AOAdmin` but you can choose whatever.

See [this StackExchange answer](https://magento.stackexchange.com/a/195091/28169) for more details.

**Comment by quickshiftin** [comment]
Hi! Can you verify this is still an issue with version 1.1.0 of the extension?
